---
project_name: portfolio-devops
docker_compose_version: "2.24.0"
kubectl_version: "1.29.0"
minikube_version: "1.32.0"
jenkins_version: "lts"
node_version: "20"

docker_hub_username: "vrushabhm"
docker_hub_password: "{{ lookup('env', 'DOCKER_HUB_PASSWORD') }}"

app_dir: /opt/portfolio
repo_url: "https://github.com/VrushabhMK/portfolio-devops.git"

aws_region: "us-east-1"
aws_account_id: "968138089440"
s3_bucket: "portfolio-devops-artifacts-968138089440"
