pipeline {
    agent any

    stages {

        stage('Checkout Code') {
            steps {

                echo '=== Cloning GitHub Repository ==='

                git branch: 'main',
                    url: 'https://github.com/VrushabhMK/portfolio-devops.git'
            }
        }

        stage('Verify Project Structure') {
            steps {

                echo '=== Checking Project Files ==='

                sh '''
                    pwd
                    ls
                    ls frontend || true
                    ls backend || true
                    ls kubernetes || true
                    ls terraform || true
                    ls ansible || true
                '''
            }
        }

        stage('Verify Docker Configuration') {
            steps {

                echo '=== Checking Docker Files ==='

                sh '''
                    ls docker-compose.yml || true
                    ls frontend/Dockerfile || true
                    ls backend/Dockerfile || true
                '''
            }
        }

        stage('Verify Kubernetes Files') {
            steps {

                echo '=== Checking Kubernetes Manifests ==='

                sh '''
                    ls kubernetes/*.yaml || true
                '''
            }
        }

        stage('CI Pipeline Complete') {
            steps {

                echo '=== DevOps CI Pipeline Executed Successfully ==='
            }
        }
    }

    post {

        success {
            echo '=== PIPELINE SUCCESS ==='
        }

        failure {
            echo '=== PIPELINE FAILED ==='
        }

        always {
            cleanWs()
        }
    }
}
